# Generated by Django 5.1.3 on 2025-11-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departmet',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_on',
            new_name='booked_on',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='doc_name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_email',
            new_name='patient_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='p_phone',
            new_name='patient_phone',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='def_display_name',
            new_name='department_description',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='def_image',
            new_name='department_image',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='def_name',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_department',
            new_name='doctor_department',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_image',
            new_name='doctor_image',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_name',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_specialization',
            new_name='doctor_specialization',
        ),
    ]
