# Generated by Django 5.1.4 on 2025-06-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_recentnews_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doc_description',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doc_experience',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='doc_fee',
        ),
    ]
