# Generated by Django 5.1.4 on 2025-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_remove_doctor_doc_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmet',
            name='def_image',
            field=models.ImageField(default='img', upload_to='images/'),
        ),
    ]
